import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fr';

export interface Player {
  id: string;
  name: string;
  isActive?: boolean;
  score?: number;
}

interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  players: Player[];
  setPlayers: (players: Player[]) => void;
  t: (key: string) => string;
}

const AppContext = createContext<AppContextType | undefined>(undefined);

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    'app-title': 'Game Night',
    'app-sub': 'Choose your game',
    'lang-label': 'Language',
    'players-label': 'Players',
    'games-label': 'Games',
    'uc-title': 'Undercover',
    'uc-desc': "Find the spy hiding among civilians before it's too late.",
    'new-game-title': 'New game',
    'coming-soon': 'Soon',
    'coming-soon-desc': 'Another game is coming...',
    'player-input-placeholder': 'Player name',
    'player-name-placeholder': 'Enter name...',
    'add-player': 'Add',
    'add-player-btn': 'Add',
    'err-empty': 'Please enter a name.',
    'err-duplicate': 'This name is already in the list.',
    'err-not-enough': 'At least 3 active players are required to play Undercover.',
    'err-not-enough-2': 'At least 2 active players are required to play.',
    'err-not-enough-mrwhite': 'At least 3 players are required to include Mr. White.',
    'min-players': '(Min {0} players)',
    'start-game': 'Start game',
    'back': 'Back',
    'next': 'Next',
    'civilians-win': 'Civilians win!',
    'undercover-wins': 'Undercovers win!',
    'mrwhite-wins': 'Mr. White wins!',
    'role-civilian': 'Civilian',
    'role-undercover': 'Undercover',
    'role-mrwhite': 'Mr. White',
    'end-title': 'Game Over',
    'roles-recap': 'Roles Summary',
    'active-label': 'Players active',
    'reveal-word': 'Reveal word',
    'hide-word': 'HIDE WORD',
    'pass-title': 'Pass the device',
    'pass-device-desc': 'Pass the device to this player to reveal their secret word.',
    'your-secret-word': 'Your secret word is',
    'you-have-no-word': 'You have no word!',
    'keep-it-secret': 'Keep it secret • Stay alert',
    'round-label': 'Round',
    'word-check-btn': 'Word Check',
    'word-check-title': 'Word Check',
    'word-check-desc': 'Select who wants to check their word. Beware of cheaters!',
    'word-checked': 'Checked {0} times',
    'word-rechecked': 'Rechecked {0} times',
    'secret-word-for': 'Secret word for {0}',
    'done-btn': 'Done',
    'game-settings': 'Game Settings',
    'customise-match': 'Customise your match',
    'undercovers': 'Undercovers',
    'mr-white': 'Mr. White',
    'hide-words': 'Hide words from host',
    'word-language': 'Word language',
    'word-pair': 'Word Pair',
    'civilian-word': 'Civilian word',
    'undercover-word': 'Undercover word',
    'suggest-words': '+ Generate new words',
    'random-pair-desc': 'A random pair will be chosen automatically based on the language.',
    'play-again': 'Play again',
    'exit-to-home': 'Exit to home',
    'mrwhite-elimination': 'Mr. White Elimination',
    'mrwhite-guess-desc': 'Can you guess the secret civilian word and steal the victory?',
    'mrwhite-guess-btn': 'Word guessed!',
    'mrwhite-dont-know-btn': 'Failed to guess',
    'give-clue-vote': 'Give your clue, then vote for the suspect!',
    'role-civilian-desc': 'Share a common word. Describe it without giving it away.',
    'role-undercover-desc': 'Have a different word. Try to blend in and guess the civilian word!',
    'role-mrwhite-desc': 'Has no word at all! Listen carefully to clues and try to steal the win by guessing the secret word.',
    'suggested-count': 'Suggested: {0}',
    'score-label': 'Score',
    'score-pts': 'pts',
    'game-master': 'Game Master',
    'none': 'None',
    'is-mj': 'MJ',
    'select-mj': 'Select Game Master',
    'mj-desc': 'The MJ knows everything and doesn\'t play. They hide words from others.',
    'change-mj': 'Change MJ?',
    'undercover-guess-title': 'Bonus: Guess word!',
    'undercover-guess-desc': 'You were eliminated, but can win 1 bonus pt by guessing the civilian word.',
    'guess-bonus-win': 'Word guessed!',
    'guess-bonus-fail': 'Failed to guess.',
    'undercover-win-guess-title': 'Final Guess!',
    'undercover-win-guess-desc': 'The undercovers have won the round! Can they guess the civilian word to double their points?',
    'undercover-guess-success': 'Word guessed!',
    'undercover-guess-fail': 'Failed to guess.',
    'confirm-quit': 'Quit game?',
    'confirm-quit-desc': 'Are you sure you want to quit? Progress will be lost.',
    'continue-playing': 'Continue',
    'mj-no-points': 'MJ (No pts)',
    'mj-required-error': 'Select a Game Master to continue',
    'edit-players': 'Edit Players',
    'language': 'Language',
    'rules': 'Rules',
    'mlt-rules-title': 'Most Likely To: Rules',
    'mlt-rules-desc': 'Players take turns reading or seeing a "Who is most likely to..." question. On the count of three, everyone points to the person they think fits the description best. The person with the most fingers pointed at them takes a point (or follows your custom drinking rules!).',
    'game-421-rules-title': '421: Rules',
    'game-421-rules-desc': 'A classic French dice game. The goal is to reach 21 points by rolling specific combinations. 4-2-1 is the best score. Rounds continue until one player reaches the target score.',
    'err-not-enough-manage': 'Would you like to manage players or return to the menu?',
    'bonus-point': 'Bonus',
    'winner-pts': '+{0} pts',
    'reset-scores': 'Reset Scores',
    'confirm-reset': 'Reset all scores?',
    'confirm-reset-desc': 'Are you sure you want to reset all player scores to zero? This cannot be undone.',
    'cancel': 'Cancel',
    'reset': 'Reset',
    'mlt-title': 'Who Would?',
    'mlt-desc': 'Point at the person who fits the description best!',
    'mlt-mode': 'Category',
    'mlt-mode-soft': 'Soft',
    'mlt-mode-hard': 'Hard',
    'mlt-mode-hot': 'Hot',
    'mlt-start': 'Start Playing',
    'mlt-next': 'Next Question',
    'mlt-skip': 'Skip',
    'mlt-vote-for': 'Who is it?',
    'mlt-add-point': 'Add +1 to {0}',
    'mlt-cat-habits': 'Habits',
    'mlt-cat-adventure': 'Adventure',
    'mlt-cat-career': 'Career',
    'mlt-cat-social': 'Social',
    'mlt-cat-party': 'Party',
    'mlt-cat-hot': 'Hot',
    'mlt-no-category-selected': 'Select at least one category',
    'killer-title': 'The Killer',
    'killer-desc': 'Each player is assigned a secret target. Convince others to eliminate yours!',
    'nhie-title': 'Never Have I Ever',
    'nhie-desc': 'WORK IN PROGRESS',
    'nhie-categories': 'Categories',
    'nhie-cat-habits': 'Habits',
    'nhie-cat-adventure': 'Adventure',
    'nhie-cat-career': 'Career',
    'nhie-cat-social': 'Social',
    'nhie-cat-party': 'Party',
    'nhie-cat-hot': 'Hot',
    'nhie-rules-title': 'Never Have I Ever: Rules',
    'nhie-rules-desc': 'WORK IN PROGRESS',
    'nhie-start': 'Start',
    'nhie-next': 'Next',
    'nhie-mode-soft': 'Soft',
    'nhie-mode-hard': 'Hard',
    'killer-role-killer': 'Killer',
    'killer-role-white-wolf': 'White Wolf',
    'killer-target-label': 'Your target is:',
    'killer-no-target': 'You have no target.',
    'killer-target-eliminated': 'Target eliminated!',
    'killer-victory-wolf': 'The White Wolf survived and wins!',
    'killer-eliminated': 'Eliminated',
    'killer-survived': 'Survived',
    'killer-round': 'Round {0}',
    'killer-rules': 'Rules',
    'killer-rules-desc': 'Assign targets. Every turn, vote to eliminate one person. If your target is eliminated, you win points!',
    'killer-white-wolf-on': 'Include White Wolf',
    'killer-white-wolf-desc': 'One player will have no target. If they survive, they win big!',
    'killer-how-to-win': 'How to win points: First round elimination (+3), Second round (+2), Third or more (+1). White Wolf (+2 if surviving).',
    'killer-mode': 'Game Mode',
    'killer-mode-classic': 'Classic (Vote)',
    'killer-mode-word': 'Word (Make them say it)',
    'killer-mode-action': 'Action (Make them do it)',
    'killer-mode-desc-classic': 'Standard mode. Eliminate targets by voting them out each round.',
    'killer-mode-desc-word': 'Make your target say a secret word from the list.',
    'killer-mode-desc-action': 'Make your target perform a specific simple action.',
    'random-targets': 'Random Allocation',
    'random-targets-desc': 'Multiple people can have the same target assigned randomly.',
    'killer-rules-intro': 'In "Killer", each player has a secret MISSION. Eliminate your target while staying discrete!',
    'killer-intro-classic': 'Classic: The group votes each round to eliminate a suspect. Each killer wants their target to be voted out.',
    'killer-intro-word': 'Word: You are given a secret word. Lead the conversation so your target says it naturally.',
    'killer-intro-action': 'Action: You are given a simple action. You must make your target do it.',
    'killer-intro-wolf': 'The White Wolf: A secret player with no target and NO ONE targets them. Others can unmask you. If unmasked, everyone else gets 1 pt. If you survive until the end, you get 3 pts!',
    'killer-unmask-wolf': 'Unmask White Wolf',
    'killer-wolf-unmasked': 'White Wolf Unmasked!',
    'killer-everyone-wins-pt': 'Everyone else +1 pt',
    'killer-wolf-survived-bonus': 'Survived (+3 pts)',
    'killer-unmask-confirm': 'Are you sure? Identify the White Wolf to win points for everyone else!',
    'killer-target-action': 'Secret Action:',
    'killer-round-label': 'Current Round',
    'killer-action-performed': 'Action done',
    'killer-word-said': 'Word said',
    'finish-game': 'Finish Game',
    'game-421-title': '421',
    'game-421-desc': 'Roll three dice and try to get a 4, a 2, and a 1!',
    'roll-dice': 'Roll Dice',
    'rolls-left': '{0} rolls left',
    'win-421': '421! You win!',
    'lose-421': 'Better luck next time!',
    'retry': 'Try Again',
  },
  fr: {
    'app-title': 'Soirée Jeux',
    'app-sub': 'Choisissez votre jeu',
    'lang-label': 'Langue',
    'players-label': 'Joueurs',
    'games-label': 'Jeux',
    'uc-title': 'Undercover',
    'uc-desc': "Trouvez l'espion caché parmi les civils avant qu'il ne soit trop tard.",
    'new-game-title': 'Nouveau jeu',
    'coming-soon': 'Prochainement',
    'coming-soon-desc': 'Un autre jeu arrive bientôt...',
    'player-input-placeholder': 'Nom du joueur',
    'player-name-placeholder': 'Entrez un nom...',
    'add-player': 'Ajouter',
    'add-player-btn': 'Ajouter',
    'err-empty': 'Veuillez entrer un nom.',
    'err-duplicate': 'Ce nom est déjà dans la liste.',
    'err-not-enough': 'Au moins 3 joueurs actifs sont nécessaires pour jouer à Undercover.',
    'err-not-enough-2': 'Au moins 2 joueurs actifs sont nécessaires pour jouer.',
    'err-not-enough-mrwhite': 'Au moins 3 joueurs sont nécessaires pour inclure Mr. White.',
    'min-players': '(Min {0} joueurs)',
    'start-game': 'Commencer',
    'back': 'Retour',
    'next': 'Suivant',
    'civilians-win': 'Les civils gagnent !',
    'undercover-wins': 'Les infiltrés gagnent !',
    'mrwhite-wins': 'Mr. White gagne !',
    'role-civilian': 'Civil',
    'role-undercover': 'Infiltré',
    'role-mrwhite': 'Mr. White',
    'end-title': 'Partie Terminée',
    'roles-recap': 'Récapitulatif des rôles',
    'active-label': 'Joueurs actifs',
    'reveal-word': 'Voir mon mot',
    'hide-word': 'CACHER LE MOT',
    'pass-title': 'Passez le téléphone',
    'pass-device-desc': 'Passez le téléphone à ce joueur pour révéler son mot secret.',
    'your-secret-word': 'Votre mot secret est',
    'you-have-no-word': 'Vous n\'avez aucun mot !',
    'keep-it-secret': 'Gardez-le secret • Restez sur vos gardes',
    'round-label': 'Tour',
    'word-check-btn': 'Vérifier son mot',
    'word-check-title': 'Vérification',
    'word-check-desc': 'Sélectionnez qui veut vérifier son mot. Attention aux tricheurs !',
    'word-checked': 'Vérifié {0} fois',
    'word-rechecked': 'Revérifié {0} fois',
    'secret-word-for': 'Mot secret de {0}',
    'done-btn': 'Terminé',
    'game-settings': 'Paramètres de la partie',
    'customise-match': 'Personnalisez votre partie',
    'undercovers': 'Infiltrés',
    'mr-white': 'Mr. White',
    'hide-words': 'Cacher les mots à l\'hôte',
    'word-language': 'Langue des mots',
    'word-pair': 'Paire de mots',
    'civilian-word': 'Mot civil',
    'undercover-word': 'Mot infiltré',
    'suggest-words': '+ Générer d\'autres mots',
    'random-pair-desc': 'Une paire aléatoire sera choisie automatiquement en fonction de la langue.',
    'play-again': 'Rejouer',
    'exit-to-home': 'Quitter',
    'mrwhite-elimination': 'Élimination de Mr. White',
    'mrwhite-guess-desc': 'Pouvez-vous deviner le mot civil et voler la victoire ?',
    'mrwhite-guess-btn': 'Mot trouvé !',
    'mrwhite-dont-know-btn': 'Mot non trouvé',
    'give-clue-vote': 'Donnez votre indice, puis votez !',
    'role-civilian-desc': 'Partagez un mot commun. Décrivez-le sans le révéler.',
    'role-undercover-desc': 'Ayez un mot différent. Essayez de vous fondre dans la masse et de deviner le mot civil !',
    'role-mrwhite-desc': 'N\'a aucun mot ! Écoutez attentivement les indices et essayez de voler la victoire en devinant le mot secret.',
    'suggested-count': 'Suggéré : {0}',
    'score-label': 'Score',
    'score-pts': 'pts',
    'game-master': 'Maître du Jeu',
    'none': 'Aucun',
    'is-mj': 'MJ',
    'select-mj': 'Choisir le MJ',
    'mj-desc': 'Le MJ sait tout et ne joue pas. Il cache les mots aux autres.',
    'change-mj': 'Changer de MJ ?',
    'undercover-guess-title': 'Bonus : Devinez le mot !',
    'undercover-guess-desc': 'Éliminé, mais gagnez 1pt bonus en devinant le mot civil.',
    'guess-bonus-win': 'Mot trouvé !',
    'guess-bonus-fail': 'Mot non trouvé.',
    'undercover-win-guess-title': 'Dernière chance !',
    'undercover-win-guess-desc': 'Les infiltrés ont gagné ! Peuvent-ils deviner le mot civil pour doubler leurs points ?',
    'undercover-guess-success': 'Mot trouvé !',
    'undercover-guess-fail': 'Mot non trouvé.',
    'confirm-quit': 'Quitter ?',
    'confirm-quit-desc': 'Voulez-vous vraiment quitter ? La progression sera perdue.',
    'continue-playing': 'Continuer',
    'mj-no-points': 'MJ (Pas de pts)',
    'mj-required-error': 'Sélectionnez un MJ pour continuer',
    'edit-players': 'Gérer les joueurs',
    'language': 'Langue',
    'rules': 'Règles',
    'mlt-rules-title': 'Qui pourrait : Règles',
    'mlt-rules-desc': 'Les joueurs lisent une question "Qui pourrait le plus...". À trois, tout le monde pointe du doigt la personne qui correspond le mieux. Celui qui a le plus de doigts pointés vers lui gagne un point (ou suit vos règles de boisson personnalisées !).',
    'game-421-rules-title': '421 : Règles',
    'game-421-rules-desc': 'Un jeu de dés classique. Le but est d\'atteindre 21 points en lançant des combinaisons spécifiques. 4-2-1 est le meilleur score. Les manches continuent jusqu\'à ce qu\'un joueur atteigne le score cible.',
    'err-not-enough-manage': 'Voulez-vous gérer les joueurs ou retourner au menu ?',
    'bonus-point': 'Bonus',
    'winner-pts': '+{0} pts',
    'reset-scores': 'Réinitialiser scores',
    'confirm-reset': 'Réinitialiser les scores ?',
    'confirm-reset-desc': 'Voulez-vous vraiment remettre tous les scores à zéro ? Cette action est irréversible.',
    'cancel': 'Annuler',
    'reset': 'Réinitialiser',
    'mlt-title': 'Qui pourrait',
    'mlt-desc': 'Pointez du doigt celui qui correspond le mieux !',
    'mlt-mode': 'Catégorie',
    'mlt-mode-soft': 'Soft',
    'mlt-mode-hard': 'Hard',
    'mlt-mode-hot': 'Hot',
    'mlt-start': 'C\'est parti !',
    'mlt-next': 'Question suivante',
    'mlt-skip': 'Passer',
    'mlt-vote-for': 'Qui a été désigné ?',
    'mlt-add-point': 'Ajouter +1 à {0}',
    'mlt-cat-habits': 'Habitudes',
    'mlt-cat-adventure': 'Aventure',
    'mlt-cat-career': 'Carrière',
    'mlt-cat-social': 'Relations',
    'mlt-cat-party': 'Soirée',
    'mlt-cat-hot': 'Sexuel',
    'mlt-no-category-selected': 'Choisissez au moins une catégorie',
    'killer-title': 'The Killer',
    'killer-desc': 'Chaque joueur a une cible secrète. Convainquez les autres d\'éliminer la vôtre !',
    'nhie-title': 'Never Have I Ever',
    'nhie-desc': 'WORK IN PROGRESS',
    'nhie-categories': 'Catégories',
    'nhie-cat-habits': 'Habitudes',
    'nhie-cat-adventure': 'Aventure',
    'nhie-cat-career': 'Carrière',
    'nhie-cat-social': 'Relations',
    'nhie-cat-party': 'Soirée',
    'nhie-cat-hot': 'Sexuel',
    'nhie-rules-title': 'Never Have I Ever: Règles',
    'nhie-rules-desc': 'WORK IN PROGRESS',
    'nhie-start': 'Commencer',
    'nhie-next': 'Suivant',
    'nhie-mode-soft': 'Soft',
    'nhie-mode-hard': 'Hard',
    'killer-role-killer': 'Killer',
    'killer-role-white-wolf': 'Loup Blanc',
    'killer-target-label': 'Ta cible est :',
    'killer-no-target': 'Tu n\'as pas de cible.',
    'killer-survived': 'Survécu',
    'killer-target-eliminated': 'Cible éliminée !',
    'killer-victory-wolf': 'Le Loup Blanc a survécu et gagne !',
    'killer-eliminated': 'Éliminé',
    'killer-round': 'Tour {0}',
    'killer-rules': 'Règles',
    'killer-rules-desc': 'Assignez des cibles. Chaque tour, votez pour éliminer une personne.',
    'killer-white-wolf-on': 'Inclure le Loup Blanc',
    'killer-white-wolf-desc': 'Un joueur n\'aura pas de cible. S\'il survit, il gagne gros !',
    'killer-how-to-win': 'Points : Élimination 1er tour (+3), 2ème tour (+2), puis (+1). Loup Blanc (+3 s\'il n\'est pas démasqué).',
    'killer-mode': 'Mode de jeu',
    'killer-mode-classic': 'Classique (Vote)',
    'killer-mode-word': 'Mot (Lui faire dire)',
    'killer-mode-action': 'Action (Lui faire faire)',
    'killer-mode-desc-classic': 'Standard. Éliminez vos cibles en votant pour elles lors des tours d\'élimination.',
    'killer-mode-desc-word': 'Faites dire à votre cible un mot secret tiré au sort.',
    'killer-mode-desc-action': 'Faites effectuer à votre cible une action simple.',
    'random-targets': 'Ciblage Aléatoire',
    'random-targets-desc': 'Plusieurs personnes peuvent avoir la même cible (attribué aléatoirement).',
    'killer-rules-intro': 'Dans "Killer", chaque joueur a une MISSION secrète. Votre but est d\'éliminer votre cible selon le mode de jeu, tout en restant discret !',
    'killer-intro-classic': 'Classique : Le groupe vote à chaque tour pour éliminer un suspect. Votre but est que votre cible soit éliminée par le vote.',
    'killer-intro-word': 'Mot : On vous donne un mot secret. Vous devez mener la conversation pour que votre cible le dise naturellement.',
    'killer-intro-action': 'Action : On vous donne une action simple. Vous devez faire faire cette action à votre cible.',
    'killer-intro-wolf': 'Le Loup Blanc : Joueur secret sans cible et PERSONNE ne le cible. Les autres peuvent le démasquer. S\'il est démasqué, tout le monde gagne 1 pt. S\'il survit sans être démasqué, il gagne 3 pts !',
    'killer-unmask-wolf': 'Démasquer le Loup Blanc',
    'killer-wolf-unmasked': 'Loup Blanc Démasqué !',
    'killer-everyone-wins-pt': 'Tout le monde +1 pt',
    'killer-wolf-survived-bonus': 'Pas démasqué (+3 pts)',
    'killer-unmask-confirm': 'Êtes-vous sûr ? Identifiez le Loup Blanc pour faire gagner 1 point à tous les autres !',
    'killer-target-word': 'Mot secret :',
    'killer-target-action': 'Action secrète :',
    'killer-round-label': 'Tour actuel',
    'killer-action-performed': 'Action faite',
    'killer-word-said': 'Mot dit',
    'finish-game': 'Terminer la partie',
    'game-421-title': '421',
    'game-421-desc': 'Lancez les dés et tentez de faire un 4, un 2 et un 1 !',
    'roll-dice': 'Lancer les dés',
    'rolls-left': '{0} lancers restants',
    'win-421': '421 ! C\'est gagné !',
    'lose-421': 'Dommage, réessaie !',
    'retry': 'Réessayer',
  }
};

export function AppProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('uc_lang');
    return (saved as Language) || 'en';
  });

  const [players, setPlayers] = useState<Player[]>(() => {
    const saved = localStorage.getItem('uc_players');
    return saved ? JSON.parse(saved) : [];
  });

  useEffect(() => {
    localStorage.setItem('uc_lang', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem('uc_players', JSON.stringify(players));
  }, [players]);

  const t = (key: string) => {
    return TRANSLATIONS[language][key] || key;
  };

  return (
    <AppContext.Provider value={{ language, setLanguage, players, setPlayers, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useAppContext() {
  const context = useContext(AppContext);
  if (!context) throw new Error('useAppContext must be used within AppProvider');
  return context;
}
